language: python
python:
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- pip install -r ci_requirements.txt
script:
- coverage run --source='outlier_detector' -m unittest test/*.py
after_success:
- codecov
deploy:
  provider: pypi
  user: docet85
  password:
    secure: KGf5U3vHkOfNl/JaRargrTkPi1vwzUd/9wQZMGinpAV4+XkVQYOT+pXpe6FH30YKDWk+nAFjhkocH9JSr+56V6vhUsNBxiiLpmmgKm4NpMMajB70UMRy+XBY3YzHUDjJ/2AQIQfU87bNGhxqHM2fMd7m0xx1jW3SwBw3Z3SDM1mEC2YjzN8AydK8ne78cDd3t+s5giHRqr267tdAMcrDvS9gsJ+tccCQTdEQ6fD4NjGs+y1IFk0fZ+vtXo7YgZpEpZQTVIwjTE4Uxl3SwFguaxnh8PWcOtAT7lszAwwxvqev1A62Ax5CEqyjHqxtqzae7lHaNOTRVJw0zs4cl5bs6NP48qWPm3tS7+sKDafEtHq/aKlx6NmfapTnix+pkpKXaz/qli4NdkT3BAWXzuPfaAXOK076XSfKUMI+YAeQIlN+u3fq7i7ZoiOv1FYxDu/TMjZxsUUE9N+wXXv01Xhk/ZdJ5vJ4/dXHXZTOEONemk2cYSsdG528di0JDPaCZkZSAyv6aAjdLg40CWiuBhnBNOGQ/5+q3Ct+KBIvt5k6BguewGILL6GPjW/r26m3L4HoNVuqXetXBANtVPtIeV2aoml5URIS8B4oFI2/Ou7uoHHaKxbi6J+FvTrX97lSedO/uFcfLMW1rOKc8nR/dETvH16xOmmzwbwAiZpCf+X9uys=
  on:
    tags: true
